name: 'Build and Release'

on:
  push:
    branches:
      - master

jobs:
  cdBuild:
    name: 'build'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run a one-line script
        run: ./cd-scripts/cdBuild.sh
