name: 'Build and Release'

on:
  push:
    branches:
      - main

jobs:
  cdBuild:
    name: 'build'
    runs-on: ubuntu-latest
    steps:
      - uses: inanme/github-ci@master
      - name: Run a one-line script
        run: echo Hello, world!
